### ISSUE TITLE
Potential race in latest

### ISSUE THREAD

**Issue by mpickering** [chessai/ring-buffers#4]
https://github.com/chessai/ring-buffers/blob/master/src/RingBuffers/Internal.hs#L80

The `MVar` is not taken for the whole call to `latest` so it seems possible that `filledLength` returns a value, and then another write is perfomed before the call to `unsafeLatest`. In this case the "latest" value returned will not be the most recently added element to the buffer.

**Comment by chessai** [comment]
Good catch!
